### ISSUE TITLE
Mixed content in chrome, respec fails

### ISSUE THREAD

**Issue by tabatkins** [w3c/predefined-counter-styles#4] opened 2016-05-25 23:24 UTC
You're linking to ReSpec over http, but the spec is https. Chrome, at least, blocks the script from running, so ReSpec doesn't get run and we're left with a bad text document.

**Comment by upsuper** [comment] 2016-05-26 01:08
That [happened](https://github.com/w3c/clreq/commit/5a4e5c0c5c449f6bf8106e9ab0fafa2f8860ab21) in [w3c/clreq](https://github.com/w3c/clreq) as well, and I guess these two are not the only specs doing so. We probably should run some script to find and update all of them.

**Comment by r12a** [comment] 2016-05-26 06:07
Thanks for the pointer.  I [updated all links](https://github.com/w3c/predefined-counter-styles/commit/a1e96cec185fc3e4f60d53dfd5c0ab847084412a) to respec and the w3c site in both docs to https. Hopefully the problem is fixed now for those docs.

Actually, the counter-styles doc looked fine to me in Chrome, so i hadn't noticed. I'll look at the other docs i maintain.

**Closed as completed by r12a** 2016-05-26 06:07 UTC
